language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "pypy3.5"
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install coveralls
script:
  - coverage run --source=swine setup.py
after_success:
- coveralls
